#!/usr/bin/env python3
"""Embeds voice/clips/*.mp3 into index.html as base64 (between the VOICE-DATA markers).
Run after adding or replacing clips:  python3 voice/embed.py"""
import base64, glob, os, re
here = os.path.dirname(os.path.abspath(__file__))
page = os.path.join(here, "..", "index.html")
clips = {os.path.basename(f)[:-4]: base64.b64encode(open(f, "rb").read()).decode() for f in sorted(glob.glob(os.path.join(here, "clips", "*.mp3")))}
body = "window.VOICE_CLIPS = {\n" + ",\n".join(f'"{k}":"{v}"' for k, v in clips.items()) + "\n};"
block = "<!-- VOICE-DATA:BEGIN (generated by voice/embed.py) -->\n<script>\n" + body + "\n</script>\n<!-- VOICE-DATA:END -->"
html = open(page).read()
if "<!-- VOICE-DATA:BEGIN" in html:
    html = re.sub(r"<!-- VOICE-DATA:BEGIN.*?<!-- VOICE-DATA:END -->", lambda m: block, html, flags=re.S)
else:
    html = html.replace("\n\n<script>\n", "\n\n" + block + "\n<script>\n", 1)
open(page, "w").write(html)
print(len(clips), "clips,", sum(len(v) for v in clips.values()) // 1024, "KB base64")
